@host = http://localhost:8000
###
POST {{host}}/v1/auth/register
Content-Type: application/json

{
  "display_name": "Ada Markets",
  "email": "ada@example.com",
  "password": "StrongerPass123!",
  "roles": ["contributor"]
}
###
POST {{host}}/v1/auth/resend-verification
Content-Type: application/json

{
  "email": "ada@example.com"
}
###
POST {{host}}/v1/auth/verify-email
Content-Type: application/json

{
  "token": "705deac1-d92f-476b-8619-433b5fb29448"
}
###
POST {{host}}/v1/auth/login
Content-Type: application/json

{
  "email": "ada@example.com",
  "password": "StrongerPass123!"
}
###
POST {{host}}/v1/auth/forgot-password
Content-Type: application/json

{
  "email": "ada@example.com"
}
###
POST {{host}}/v1/auth/reset-password
Content-Type: application/json

{
  "token": "PASTE_RESET_TOKEN_HERE",
  "new_password": "EvenStrongerPass456!"
}