@host = http://localhost:8000
###
POST {{host}}/v1/auth/register
Content-Type: application/json

{
  "display_name": "Ada Markets",
  "email": "ada@example.com",
  "password": "StrongerPass123!",
  "roles": ["contributor"]
}
###
POST {{host}}/v1/auth/resend-verification
Content-Type: application/json

{
  "email": "williamikeji@gmail.com"
}

HTTP/1.1 200  - OK
date: Tue, 16 Jun 2026 15:22:02 GMT
server: uvicorn
content-length: 109
content-type: application/json
x-request-id: e2b1d2f2-58d0-4efc-b1fc-7d03cf5450aa
connection: close
###
POST {{host}}/v1/auth/verify-email
Content-Type: application/json

{
  "token": "ev_kT-EGFI047msBthDxqu2XjUE2Bn_XLOg85kZMTGdj5k"
}

HTTP/1.1 400  - Bad Request
date: Tue, 16 Jun 2026 15:17:30 GMT
server: uvicorn
content-length: 40
content-type: application/json
x-request-id: 46839ad6-547e-463c-bf4b-d22edb25b9c8
connection: close
###
POST {{host}}/v1/auth/login
Content-Type: application/json

{
  "email": "ada@example.com",
  "password": "StrongerPass123!"
}
###
POST {{host}}/v1/auth/forgot-password
Content-Type: application/json

{
  "email": "ada@example.com"
}
###
POST {{host}}/v1/auth/reset-password
Content-Type: application/json

{
  "token": "PASTE_RESET_TOKEN_HERE",
  "new_password": "EvenStrongerPass456!"
}